spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user
          uri: http://localhost:8081/
          predicates:
            - Path=/users/**
        - id: pay
          uri: http://localhost:8082/
          predicates:
            - Path=/accounts/**
        - id: product
          uri: http://localhost:8083/
          predicates:
            - Path=/products/**, /brands/**, /interest/**
        - id: bid
          uri: http://localhost:8084/
          predicates:
            - Path=/bid/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetchRegistry: true

server:
  port: 8080