spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://user/
          predicates:
            - Path=/users/**
        - id: pay
          uri: lb://pay/
          predicates:
            - Path=/accounts/**
        - id: product
          uri: lb://product/
          predicates:
            - Path=/products/**, /brands/**, /interest/**
        - id: bid
          uri: lb://bid/
          predicates:
            - Path=/bid/**
        - id: contract
          uri: lb://contract/
          predicates:
            - Path=/contracts/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetchRegistry: true

server:
  port: 8080