spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://user/
          predicates:
            - Path=/users/**
          filters:
            - JwtAuthenticationFilter
        - id: pay
          uri: lb://pay/
          predicates:
            - Path=/accounts/**
          filters:
            - JwtAuthenticationFilter
        - id: product
          uri: lb://product/
          predicates:
            - Path=/products/**, /brands/**, /interest/**
          filters:
            - JwtAuthenticationFilter
        - id: bid
          uri: lb://bid/
          predicates:
            - Path=/bid/**
          filters:
            - JwtAuthenticationFilter
        - id: contract
          uri: lb://contract/
          predicates:
            - Path=/contracts/**
          filters:
            - JwtAuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetchRegistry: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics

server:
  port: 8080